// Verify Email
export const EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST";

export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";

export const EMAIL_VERIFICATION_FAILURE = "EMAIL_VERIFICATION_FAILURE";

export const EMAIL_VERIFICATION_CLEAR = "EMAIL_VERIFICATION_CLEAR";

// Verify Email Code
export const EMAIL_VERIFICATION_CODE_REQUEST =
  "EMAIL_VERIFICATION_CODE_REQUEST";

export const EMAIL_VERIFICATION_CODE_SUCCESS =
  "EMAIL_VERIFICATION_CODE_SUCCESS";

export const EMAIL_VERIFICATION_CODE_FAILURE =
  "EMAIL_VERIFICATION_CODE_FAILURE";

export const EMAIL_VERIFICATION_CODE_CLEAR = "EMAIL_VERIFICATION_CODE_CLEAR";

// Resend Verify Email Code

export const RESEND_EMAIL_VERIFICATION_CODE_REQUEST =
  "RESEND_EMAIL_VERIFICATION_CODE_REQUEST";

export const RESEND_EMAIL_VERIFICATION_CODE_SUCCESS =
  "RESEND_EMAIL_VERIFICATION_CODE_SUCCESS";

export const RESEND_EMAIL_VERIFICATION_CODE_FAILURE =
  "RESEND_EMAIL_VERIFICATION_CODE_FAILURE";

export const RESEND_EMAIL_VERIFICATION_CODE_CLEAR =
  "RESEND_EMAIL_VERIFICATION_CODE_CLEAR";

// Signup

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_UP_CLEAR = "SIGN_UP_CLEAR";

export const REVERT_EMAIL_VERIFICATION = "REVERT_EMAIL_VERIFICATION";
